name: 'Minify Action'
description: 'Minify code and push to another branch'

inputs:
  repo:
    description: 'Current repo'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}/script
        sudo bash minify.sh ${{github.repository}}
      shell: bash
