name: 'Minify Action'
description: 'Minify code and push to another branch'

inputs:
  push-branch:
    description: 'Branch you wanna push minified codes'
    required: true
  repo:
    description: 'Current repo'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}/script
        sudo bash minify.sh ${{ inputs.push-branch }} ${{github.repository}}
      shell: bash
