name: minify

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    env:
      pbranch: production
      prepo: ${{github.repository}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Minify Actions
      uses: amireshoon/minifyAction@main
      with:
        push-branch: $pbranch
        repo: $prepo
    - name: Running Tests
      run: |
        minifier.sh $pbranch $prepo
    - name: Commiting changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: github/workspace
        branch: env.pushed_branch
      env:
        pushed_branch: $pbranch
    name: Minify
